/*Each new term in the Fibonacci sequence is generated by adding the previous twoterms.
By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms. Ans: 4613732*/


#include<stdio.h>
void main()
{
    int fibbo =0, a1=0, a2=1, sum = 0;
    printf("The fibonacci sequence is: \n");
    while(fibbo<=4000000) {
        fibbo = a1+a2;
        if(fibbo%2==0){
            sum=sum+fibbo;
        }
        a1=a2;
        a2=fibbo;
    }
printf("\nThe sum of the series: %d", sum);
}
